---
title: "Analysis of Road Accidents to minimize future possibilities for Road mishaps"
author: "Chormi Zimik Vashai and Pavan Kumar Rudrapogu"
date: "4/14/2023"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



- Install and load required packages
```{r}
#tinytex::install_tinytex()
#install.packages("dplyr")
#install.packages("ggplot2")
#install.packages("RColorBrewer")
#install.packages("mice")
library("dplyr")
library("ggplot2")
library("RColorBrewer")
library("mice")
```
```{r}
my_data <- read.csv("freeway crashes.CSV", stringsAsFactors = FALSE)
#View(my_data)
```

```{r}
#1- Data cleansing/Wrangling

#removing columns that aren't required
new_data<-my_data[-c(2:9,12,13,10,19,20,21,22,24,25,26)]

#joiining alc and drug use column into one column called alc_drug

new_data$alc_drug <- ifelse(new_data$alch_susp_ind | new_data$drug_susp_ind, 1, 0)
#View(new_data)
#deleting alc and drug column
new_data<-new_data[-c(9,10)]
View(new_data)

#We cannot omit rows with NA in the column since 2013 data has no age filled
#we impute using mean, median and regression.
#1a Mean Imputation
mean_data<-new_data
mean_age <- mean(mean_data$prty_age, na.rm = TRUE)
mean_data$prty_age <- ifelse(is.na(mean_data$prty_age), mean_age, mean_data$prty_age)

ggplot(mean_data, aes(x = prty_age)) +
  geom_histogram(binwidth = 5, fill = "lightgreen") +
  labs(title = "Distribution of Driver Age in Accidents (2010-2017)",
       x = "Age",
       y = "Count")
# Notice the huge count in age around 38 years, which is due to mean imputing, hence not used.

#1b Median Imputation
median_data<-new_data
median_age <- median(median_data$prty_age, na.rm = TRUE)
median_data$prty_age <- ifelse(is.na(median_data$prty_age), median_age, median_data$prty_age)

ggplot(median_data, aes(x = prty_age)) +
  geom_histogram(binwidth = 5, fill = "lightgreen") +
  labs(title = "Distribution of Driver Age in Accidents (2010-2017)",
       x = "Age",
       y = "Count")
# Notice the huge count in age around 38 years, which is due to median imputing, hence not used.


#1c Multiple impute using Regression method

regress_data <- mice(new_data, m = 5, method = "norm.predict") # *THIS WILL TAKE A COUPLE OF MINUTES TO LOAD SO ONLY DO IF YOU HAVE TIME*
# combine the imputed data sets
regress_data <- complete(regress_data, action = "long")

ggplot(regress_data, aes(x = prty_age)) +
  geom_histogram(binwidth = 5, fill = "lightgreen") +
  labs(title = "Distribution of Driver Age in Accidents (2010-2017)",
       x = "Age",
       y = "Count")

#Mean and median give 38.00 years for all 
#Regression give 35 to 40. Hence we decided to omit 2013 data to keep the integrity of the data for other years


#removing rows with NA value
NA_data<-new_data # data with NA values
new_data<-na.omit(new_data)
#Deleting values UNKNOWN from milt_time also
new_data <- subset(new_data, milt_time != "UNK")

#milt time is character, not numeric . hence we have to change to numeric
class(new_data$milt_time)
is.numeric(new_data$milt_time)
new_data$milt_time <- as.numeric(new_data$milt_time)
new_data<-na.omit(new_data) # removing na values where it was coerced to NA for alphabets value
View(new_data)

```


#2 Data Exploration
```{r}
#2a Checking which year has the highest accidents

# group accidents by year and count the number of accidents in each year
year_counts <- new_data %>% 
                group_by(year) %>% 
                summarise(accident_count = n())

# sort the years by the number of accidents in descending order
year_counts <- year_counts[order(-year_counts$accident_count),]

# print the year with the highest number of accidents
cat("The year with the highest number of accidents is", year_counts$year[1], "with", year_counts$accident_count[1], "accidents.")
```

```{r}

#2bChecking which age group has highest accidents

# create age groups based on the age column
new_data <- new_data %>%
  mutate(age_group = cut(prty_age, breaks = c(0, 15, 30, 45, 61, Inf), 
                         labels = c("0-15", "16-30", "31-45", "46-60","61+")))

# group accidents by age group and count the number of accidents in each group
age_counts <- new_data %>% group_by(age_group) %>% summarise(accident_count = n())

# sort the age groups by the number of accidents in descending order
age_counts <- age_counts[order(-age_counts$accident_count),]

# print the age group with the highest number of accidents
cat("The age group with the highest number of accidents is", age_counts$age_group[1], "with", age_counts$accident_count[1], "accidents.")
```

```{r}
#2c Data with fatal accidents only

fatal_accidents <- new_data %>%
  filter(injy_svty_cd == "1")
#View(fatal_accidents)
```

```{r}
#2d Finding which year has the most fatal accidents

# Group the data by year and count the number of fatal accidents
fatal_by_year <- fatal_accidents %>%
  group_by(year) %>%
  summarize(num_fatal = n())

# Find the year with the most fatal accidents
most_fatal_year <- fatal_by_year %>%
  filter(num_fatal == max(num_fatal)) %>%
  select(year)

print(most_fatal_year)
```

```{r}
#2e How many percentage of accidents happen in Clear weather(Value =1) and dry road conditions(value=1)
total_accidents <- nrow(new_data)
clear_wthr_crash <- sum(new_data$wthr_cd == 1, na.rm = TRUE)
percent_clear_wthr_crash <- 100 * clear_wthr_crash / total_accidents
print(percent_clear_wthr_crash)# 49%

clear_rd_crash<-sum(new_data$rd_cond_cd == 1, na.rm = TRUE)
percent_clear_rd_crash <- 100 * clear_rd_crash / total_accidents
print(percent_clear_rd_crash) # 62%
```

```{r}
#2f How many percentage were under alc or drug influence. 
alc_drug_crash<-sum(new_data$alc_drug == 1, na.rm = TRUE)
percent_alc_drug_crash <- 100 * alc_drug_crash / total_accidents
print(percent_alc_drug_crash) # 1.9%%
```

```{r}
#2g How severe were alc_drug accidents

alc_drug_data_fatal <- subset(new_data, injy_svty_cd == 1)
#View(alc_drug_data)
total_alc_drug_accidents <- nrow(alc_drug_data_fatal)
alc_drug_crash_fatal<-sum(alc_drug_data_fatal$alc_drug == 1, na.rm = TRUE)
percent_alc_drug_crash_fatal <- 100 * alc_drug_crash_fatal / total_alc_drug_accidents
print(percent_alc_drug_crash_fatal) #31% of alc_drug accidents are fatal
```

```{r}
#2h How severe were other accidents without alc_drug

accidents_wo_alc_drug <- new_data %>%
  filter(alc_drug == 0)

count_wo_alc_drug<-nrow(accidents_wo_alc_drug)
wo_alc_drug_crash_fatal<-sum(accidents_wo_alc_drug$injy_svty_cd == 1, na.rm = TRUE)
percent_wo_alc_drug_crash_fatal <- 100 * wo_alc_drug_crash_fatal / count_wo_alc_drug
print(percent_wo_alc_drug_crash_fatal) #0.1% of total accidents are fatal without alc_drug
```


#3 Data Visualisation Part 1

```{r}
#3a 
###
ggplot(new_data, aes(x = spd_limt)) +
  geom_histogram(binwidth = 5, fill = "steelblue") +
  labs(title = "Distribution of SPeed in Accidents (2010-2017)",
       x = "Speed",
       y = "Count")
# SPeed limit around 70 ahs most accidents
```

```{r}
#3b check distribution of Age
ggplot(new_data, aes(x = prty_age)) +
  geom_histogram(binwidth = 5, fill = "steelblue") +
  labs(title = "Distribution of Driver Age in Accidents (2010-2017)",
       x = "Age",
       y = "Count")
# Around 18-28 years old has most accidents and it starts to go down with age increase
```

```{r}
#3c checking trends on accidents by year
ggplot(NA_data, aes(x = year)) +
  geom_bar(fill = "steelblue") +
  labs(title = "Number of Accidents by Year (2010-2017)",
       x = "Year",
       y = "Number of Accidents") 
# Accidents tend to increase over each year, we use 2013 data too just to see the pattern
```

```{r}
#3d Alcohol and drug related accidents over the years
alc_dru_data<-subset(NA_data,alc_drug==1)
ggplot(alc_dru_data, aes(x = year)) +
  geom_bar(fill = "steelblue") +
  labs(title = "Number of Accidents by Year (2010-2017) related to alcohol/drug",
       x = "Year",
       y = "Number of Accidents due to alc/drug")
# seems to be unform

```

```{r}
#3e Most accident occurrence by time
ggplot(new_data, aes(x = milt_time)) +
  geom_bar(fill = "steelblue") +
  labs(x = "Time of accident (hour)", y = "Count", title = "time of accident")
# most accident occurs during 8am and 8pm
```

```{r}
#3f Checking road accidents by road condition

ggplot(new_data, aes(x = rd_cond_cd)) +
  geom_bar(fill = "steelblue") +
  labs(x = "road condition", y = "Count", title = "Accident at various road conditions")
# it seems bad road conditions dont necessarily contribute to accidents
```

```{r}
#3g Accident at various Weather conditions
ggplot(new_data, aes(x = wthr_cd)) +
  geom_bar(fill = "steelblue") +
  labs(x = "Weather condition", y = "Count", title = "Accident at various Weather conditions")
#Clear day has high chances of accident, cloudy(2),rain(4) and snow(5) together contribute nearly as equal to clear sky
```

```{r}
#3h Accident at various light conditions
ggplot(new_data, aes(x = lit_cd)) +
  geom_bar(fill = "steelblue") +
  labs(x = "Light condition", y = "Count", title = "Accident at various light conditions")
# Daylight(1) has most occurence  dark without strretlight(5) has more accidents than dark with streetlight(4)
```

```{r}
#3i Accident at various injury severity
ggplot(new_data, aes(x = injy_svty_cd )) +
  geom_bar(fill = "steelblue") +
  labs(x = "Injy_svty", y = "Count", title = "Accident at various injury severity")
 #most accidents are not fatal, though few are incapacitating(2) and non-incapacitating(3)
```

```{r}
#3j
ggplot(new_data, aes(x = num_lns )) +
  geom_bar(fill = "steelblue") +
  labs(x = "Injy_svty", y = "Count", title = "Accident at various lanes")
#
```

```{r}
#3k
ggplot(new_data, aes(x = traffic_volume )) +
  geom_bar(fill = "steelblue") +
  labs(x = "Injy_svty", y = "Count", title = "Accident at various traffic volumes")
###
```

```{r}
#3j
#which speed limit has most accident and add alc_drug use to better understand
# Grouping the accidents data by speed limit and alcohol/Drug use
speed_alcohol <- new_data %>%
  group_by(spd_limt, alc_drug) %>%
  summarize(count = n())

# Create a stacked bar chart
ggplot(speed_alcohol, aes(x = spd_limt, y = count, fill = factor(alc_drug))) +
  geom_bar(stat = "identity") +
  labs(title = "Accidents by Speed Limit and Alcohol/Drug Use",
       x = "Speed Limit", y = "Count") +
  scale_fill_manual(name = "Alcohol/Drug Use Detected", 
                    values = c("blue", "red"),
                    labels = c("No", "Yes")) 

#speed limit 70 has a lot of accidents or most roads are speed limit 70. Also alcohol/drug accidents happen at 70 speed limit mostly
```

#3 Data Visualisation Part 2

```{r}
#3a scatterplot of time of accident n age of driver with alc_drug use/no_use
ggplot(new_data, aes(x = milt_time, y = prty_age, color = alc_drug)) +
  geom_point(alpha = 0.6) +
  scale_color_gradient(low = "steelblue", high = "firebrick") +
  labs(x = "Time of accident", y = "Age of driver", title = "Relationship between time of accident and age of driver")
# Alc_drug accidents seem to happen more between 8pm to 3 am as shown by the red dots.
# more age groups tend to travel at 10 am to 3 pm.
```

```{r}
#3bScatter plot of traffic volume by age of driver, colored by alc_drug use detected:
ggplot(new_data, aes(x = prty_age, y = traffic_volume, color = factor(alc_drug))) +
  geom_point(alpha = 0.6) +
  labs(x = "Age of driver", y = "Traffic volume", title = "Traffic volume by age of driver") +
  scale_color_manual(values = c("steelblue", "firebrick"), labels = c("No", "Yes")) #low traffic volume and low age more accidents, alcohol not reqd
# confirms that alc_drug related accidents happen more in lower age groups.
#accidents occur more in less traffic area. 
```

```{r}
#3c Scatter plot of traffic volume by injury severity with alc/drug usage taken into account
ggplot(new_data, aes(x = injy_svty_cd, y = traffic_volume, color = factor(alc_drug))) +
  geom_point(alpha = 0.6) +
  labs(x = "Injury severity", y = "Traffic volume", title = "Traffic volume by injy severity") +
  scale_color_manual(values = c("steelblue", "firebrick"), labels = c("No", "Yes")) #shows alc_drug is usually related to high injy severity(1 is fatal) 
#alc_drug accidents are more fatal.
```

##3 Data Visualisation Part 3
```{r}
#3a Heatmap of Accidents by Road and Weather Condition
#Group the data by road condition and weather condition, and count the number of accidents in each group
accidents_grouped <- new_data %>% 
  group_by(rd_cond_cd, wthr_cd) %>% 
  summarise(count = n()) %>% 
  ungroup()

# Create a heatmap
ggplot(accidents_grouped, aes(x = rd_cond_cd, y = wthr_cd, fill = count)) +
  geom_tile() +
  scale_fill_gradientn(colours = brewer.pal(9, "YlOrRd"), na.value = "firebrick") +
  labs(x = "Road Condition", y = "Weather Condition", title = "Accidents by Road and Weather Condition") +  
  theme(axis.title = element_text(size = 14), axis.text = element_text(size = 12))

# this heatmap shows that accident occur the most at good weatehr and good road conditions. Notice the dark red at low value.
```

```{r}
#3b Heatmap of Accidents by Road and light Condition
accidents_grouped <- new_data %>% 
  group_by(rd_cond_cd, lit_cd) %>% 
  summarise(count = n()) %>% 
  ungroup()

# Create a heatmap
ggplot(accidents_grouped, aes(x = rd_cond_cd, y = lit_cd, fill = count)) +
  geom_tile() +
  scale_fill_gradientn(colours = brewer.pal(9, "YlOrRd"), na.value = "firebrick") +
  labs(x = "Road Condition", y = "light Condition", title = "Accidents by Road and light Condition") +
  theme(axis.title = element_text(size = 14), axis.text = element_text(size = 12))
# this heatmap shows that accident occur the most at good light and good road conditions. Notice the dark red at low value.
```

#4 Machine Learning

```{r}
#4a Loading required libraries

library(ggplot2)
#install.packages("ggcorrplot")
library(ggcorrplot)
#install.packages("FactoMineR")
library("FactoMineR")

#*#Make sure all the below libraries are up to date.
#*If you aren't sure then 'Remove' and 'Install' again
#*Remove by using "remove.packages("name_of_library")""
#*Install by using "install.packages("name_of_library")"


#install.packages('caret')
#install.packages('lattice')
library(rlang)
library(lattice)
library(caret)
library(MASS)
#remove.packages("vctrs")
#install.packages("rlang")
#remove.packages("vctrs")
#install.packages("vctrs")
#remove.packages("tibble")
#install.packages("tibble")
```

```{r}
#4b Loading data and getting some hindsight
accident_data<-new_data[,c(1:11)] #Removing the last three columns which was created from previous Data wrangling
#summary

head(accident_data)

summary(accident_data)
str(accident_data)

#View(accident_data)
```

```{r}
#4c Data normalization, scaling and Plotting the correlation matrix
# year is removed
data_for_normalization<-accident_data[,c(2:8,10:11)]

#importing Severity injury condition into "severity"
severity<-c(accident_data$injy_svty_cd)

data_normalized<-scale(data_for_normalization)
data_normalized_df <- as.data.frame(data_normalized)

df<-data.frame(data_normalized_df,severity)
#df1<-data.frame(data_normalized_df,severity)

corr_matrix <- cor(df)


#correlation matrix
ggcorrplot(corr_matrix)

#The correlation matrix shows that age seems to be un-correlated(white and blue cubes only)
```

```{r}
#4d Create a new categorical column based on the severity column
df$severity <- ifelse(df$severity == 1, "fatal", 
                      ifelse(df$severity == 2, "critical", 
                             ifelse(df$severity == 3, "severe",
                                    ifelse(df$severity == 4, "moderate", "minor"))))

# The values of severity as given by data are numeric. We have converted them into words

df$severity<-as.factor(df$severity) # asked to be in factor hence made into factor
top_df <- as.data.frame(df)
```

```{r}
#4e ORDINAL LOGISTIC REGRESSION MODEL 
set.seed(123)
train_indices<-sample(nrow(top_df),0.8*nrow(top_df)) #80% of data is used for training
train_data<-top_df[train_indices,]
test_data<-top_df[-train_indices,]

model <- polr(severity ~ wthr_cd +  lit_cd + num_lns + spd_limt + rd_cond_cd + alc_drug + traffic_volume , data = train_data)
#polr is ORDINAL LOGISTIC REGRESSION MODEL function
# age removed since no correlation
test_preds <- predict(model, newdata = test_data, type = "class")
#type=class since classifctation algo


confusionMatrix(test_preds, test_data$severity)

#The confusion matrix shows us many important information. Our algorithm has accuracy of 87.03%. The confidence interval is 95% 

#Ensembling technique-future works, with two other ML techniques

```